name: "httpx Action"
description: "httpx is a fast and multi-purpose HTTP toolkit allows to run multiple probers using retryablehttp library."
branding:
  icon: "activity"
  color: "blue"

inputs:
  list:
    description: "List of hosts to run HTTP/S Web server probbing"
    required: true
    default: ""

  output:
    description: "File to save output result"
    required: false
    default: "httpx.log"

  json:
    description: "Format to save of output file"
    required: false
    default: false

  random-ua:
    description: "Use random User-Agent"
    required: false
    default: true

  flags:
    description: "Additional httpx CLI flags to use"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/httpx ] && go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
        [ ! -z "${{ inputs.list }}" ] && echo "list=-l ${{ inputs.list}}" >> $GITHUB_ENV
        [ ! -z "${{ inputs.output }}" ] && echo "output=-o ${{ inputs.output}}" >> $GITHUB_ENV || echo "output=-o httpx.log" >> $GITHUB_ENV
        [ ! -z "${{ inputs.flags }}" ] && echo "flags=${{ inputs.flags }}" >> $GITHUB_ENV
        ${{ inputs.json }} && echo "json=-json" >> $GITHUB_ENV
        ${{ inputs.random-ua }} && echo "random-ua=-random-agent" >> $GITHUB_ENV
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash
      env:
        GOPROXY: https://proxy.golang.org,direct

    - run: |
        httpx \
          ${{ env.list }} \
          ${{ env.output }} \
          ${{ env.json }} \
          ${{ env.random-ua }} \
          ${{ env.flags }}
      shell: bash
