name: "SubFinder Action"
description: "SubFinder is a passive subdomain discovery tool that discovers valid subdomains for websites."
branding:
  icon: "activity"
  color: "blue"

inputs:
  domain:
    description: "Domain to run subdomain enumeration"
    required: true

  list:
    description: "List of domains to run subdomain enumeration"
    required: false
    default: ""

  config:
    description: "Config file to use for subdomain enumeration"
    required: false
    default: ""

  output:
    description: "File to save output result"
    required: false
    default: "subfinder.log"

  flags:
    description: "Additional subfinder CLI flags to use"
    required: false

  active:
    description: "Filter subdomains with no DNS records"
    required: false
    default: false

  json:
    description: "Format to save of output file"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Setup SubFinder
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      shell: bash
      env:
        GOPROXY: https://proxy.golang.org,direct

    - name: Run SubFinder
      run: |
        command="subfinder ${{ inputs.domain }}"
        if [ ! -z "${{ inputs.list }}" ]; then
          command="$command -dL ${{ inputs.list }}"
        fi
        if [ ! -z "${{ inputs.config }}" ]; then
          command="$command -config ${{ inputs.config }}"
        fi
        if [ ! -z "${{ inputs.output }}" ]; then
          command="$command -o ${{ inputs.output }}"
        else
          command="$command -o subfinder.log"
        fi
        if [ "${{ inputs.json }}" = true ]; then
          command="$command -json"
        fi
        if [ "${{ inputs.active }}" = true ]; then
          command="$command -nW"
        fi
        if [ ! -z "${{ inputs.flags }}" ]; then
          command="$command ${inputs.flags}"
        fi
        $command
      shell: bash
