name: "SubFinder Action"
description: "SubFinder is a passive subdomain discovery tool that discovers valid subdomains for websites."
branding:
  icon: "activity"
  color: "blue"

inputs:
  domain:
    description: "Domain to run subdomain enumeration"
    required: true

  list:
    description: "List of domains to run subdomain enumeration"
    required: false
    default: ""

  config:
    description: "Config file to use for subdomain enumeration"
    required: false
    default: ""

  output:
    description: "File to save output result"
    required: false
    default: "subfinder.log"

  flags:
    description: "Additional subfinder CLI flags to use"
    required: false

  active:
    description: "Filter subdomains with no DNS records"
    required: false
    default: false

  json:
    description: "Format to save of output file"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Setup SubFinder
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
      shell: bash
      env:
        GOPROXY: https://proxy.golang.org,direct

    - name: Run SubFinder
      run: |
        subfinder \
          ${{ inputs.domain }} \
          ${{ inputs.list }} \
          ${{ inputs.config }} \
          ${{ inputs.output }} \
          ${{ if inputs.json }} "-json" ${{ end }} \
          ${{ inputs.flags }} \
          ${{ if inputs.active }} "-nW" ${{ end }}
      shell: bash
